name: micro_learning_flashcards
description: A flashcard app for micro learning
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase dependencies (compatible and stable set)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.6
  firebase_auth_web: ^5.8.8
  cloud_firestore: ^4.15.8

  # ✅ State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # ✅ Utilities
  uuid: ^3.0.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.4
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.9.2 

flutter:
  uses-material-design: true
